classes:
  - fret_0
  - fret_1
  - fret_2
  - fret_3
  - fret_4
  - fret_5
  - fret_6
  - fret_7
  - fret_8
  - fret_9
  - fret_10
  - fret_11
  - fret_12
  - fret_13
  - fret_14
  - fret_15
  - fret_16
  - fret_17
  - fret_18
  - fret_19
  - fret_20
  - fret_21
  - fret_22
  - dead_note
